-------------------------------------------------------------------------------
Test set: dev.model.exception.NoSORMIDFoundExceptionTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
